Repository GDSC-BSIOTR/Fly-Learn, pull requests merged in 2021-10, with the labels that each got.

#20 Update index.json
  index.json
Labels: hacktoberfest-accepted

#21 Update index.json
  index.json
Labels: hacktoberfest-accepted

#22 Added course id 24
  index.json
Labels: hacktoberfest-accepted

#25 Added one More
  index.json
Labels: Hacktoberfest

#23 Update index.json
  index.json
Labels: hacktoberfest-accepted

#24 Update index.json
  index.json
Labels: hacktoberfest-accepted

#26 Update index.json
  index.json
Labels: hacktoberfest-accepted

#27 Update index.json
  index.json
Labels: hacktoberfest-accepted

#30 Update index.json
  index.json
Labels: hacktoberfest-accepted

#29 index.json
  index.json
Labels: hacktoberfest-accepted

#31 Update index.json
  index.json
Labels: hacktoberfest-accepted

#32 Update index.json
  index.json
Labels: hacktoberfest-accepted

#33 Update index.json
  index.json
Labels: hacktoberfest-accepted

#35 Update index.json
  index.json
Labels: hacktoberfest-accepted

#37 Update index.json
  index.json
Labels: hacktoberfest-accepted

#36 Update index.json
  index.json
Labels: hacktoberfest-accepted

#38 solved my mistake 1
  index.json
Labels: hacktoberfest-accepted

#40 Add Id 37
  index.json
Labels: invalid

#41 Update Index. json
  index.json
Labels: invalid

#42 Added id:35
  index.json
Labels: hacktoberfest-accepted
